export const Users = [
  {
    id: 1,
    profilePicture: 'assets/person/1.jpeg',
    username: 'Bam Khatri',
  },
  {
    id: 2,
    profilePicture: 'assets/person/2.jpeg',
    username: 'Abhishek Joshi',
  },
  {
    id: 3,
    profilePicture: 'assets/person/3.jpeg',
    username: 'Samip Roka',
  },
  {
    id: 4,
    profilePicture: 'assets/person/4.jpeg',
    username: 'Sushil Bhattrai',
  },
  {
    id: 5,
    profilePicture: 'assets/person/5.jpeg',
    username: 'Shankar Dhungana',
  },
  {
    id: 6,
    profilePicture: 'assets/person/6.jpeg',
    username: 'Manoj BK',
  },
  {
    id: 7,
    profilePicture: 'assets/person/7.jpeg',
    username: 'Bijay Poudel',
  },
  {
    id: 8,
    profilePicture: 'assets/person/8.jpeg',
    username: 'Ayus Timelsena',
  },
  {
    id: 9,
    profilePicture: 'assets/person/9.jpeg',
    username: 'Hari Sharma',
  },
  {
    id: 10,
    profilePicture: 'assets/person/10.jpeg',
    username: 'Ram Karki',
  },
]

export const Posts = [
  {
    id: 1,
    desc: 'Love For All,Hatred For None',
    photo: 'assets/post/1.jpeg',
    date: '5 min ago',
    userId: 1,
    like: 13,
    comment: 1,
  },
  {
    id: 2,
    desc: "What's Going on ",
    photo: 'assets/post/2.jpeg',
    date: '10 min ago',
    userId: 2,
    like: 20,
    comment: 4,
  },
  {
    id: 3,
    desc: 'Hey! There',
    photo: 'assets/post/3.jpeg',
    date: '16 min ago',
    userId: 3,
    like: 25,
    comment: 6,
  },
  {
    id: 4,
    desc: '',
    photo: 'assets/post/4.jpeg',
    date: '1 hour ago',
    userId: 4,
    like: 30,
    comment: 13,
  },
  {
    id: 5,
    desc: 'No Pain No Gain',
    photo: 'assets/post/5.jpeg',
    date: '1 day ago',
    userId: 5,
    like: 50,
    comment: 17,
  },
  {
    id: 6,
    desc: 'Time Doesnot Wait For Anyone',
    photo: 'assets/post/6.jpeg',
    date: '1 day and 2 hours ago',
    userId: 6,
    like: 62,
    comment: 19,
  },
  {
    id: 7,
    desc: 'What Is The Meaning Of Life',
    photo: 'assets/post/7.jpeg',
    date: '1 day and 2 hours ago',
    userId: 7,
    like: 62,
    comment: 19,
  },
  {
    id: 8,
    desc: '',
    photo: 'assets/post/8.jpeg',
    date: '1 day and 2 hours ago',
    userId: 8,
    like: 70,
    comment: 23,
  },
  {
    id: 9,
    desc: 'Kehi Vanu Xa Yesma',
    photo: 'assets/post/9.jpeg',
    date: '1 day and 3 hours ago',
    userId: 9,
    like: 83,
    comment: 27,
  },
  {
    id: 10,
    desc: 'Nothing Last Forever',
    photo: 'assets/post/10.jpeg',
    date: '1 day and 4 hours ago',
    userId: 10,
    like: 90,
    comment: 25,
  },
]
